//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Epsilon.Resources.Web.Token
{


    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class TokenResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal TokenResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Epsilon.Resources.Web.Token.TokenResources", typeof(TokenResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Amount.
        /// </summary>
        public static string MyTokenTransactions_ColumnAmount_Header {
            get {
                return ResourceManager.GetString("MyTokenTransactions_ColumnAmount_Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Made On.
        /// </summary>
        public static string MyTokenTransactions_ColumnMadeOn_Header {
            get {
                return ResourceManager.GetString("MyTokenTransactions_ColumnMadeOn_Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quantity.
        /// </summary>
        public static string MyTokenTransactions_ColumnQuantity_Header {
            get {
                return ResourceManager.GetString("MyTokenTransactions_ColumnQuantity_Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type.
        /// </summary>
        public static string MyTokenTransactions_ColumnRewardType_Header {
            get {
                return ResourceManager.GetString("MyTokenTransactions_ColumnRewardType_Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to My Token Transactions.
        /// </summary>
        public static string MyTokenTransactions_Header {
            get {
                return ResourceManager.GetString("MyTokenTransactions_Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loading....
        /// </summary>
        public static string MyTokenTransactions_LoadingMessage {
            get {
                return ResourceManager.GetString("MyTokenTransactions_LoadingMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Token Rewards.
        /// </summary>
        public static string Rewards_PageTitle {
            get {
                return ResourceManager.GetString("Rewards_PageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Description.
        /// </summary>
        public static string TokenRewardsSummary_ColumnDescription_Header {
            get {
                return ResourceManager.GetString("TokenRewardsSummary_ColumnDescription_Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type.
        /// </summary>
        public static string TokenRewardsSummary_ColumnRewardType_Header {
            get {
                return ResourceManager.GetString("TokenRewardsSummary_ColumnRewardType_Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Amount.
        /// </summary>
        public static string TokenRewardsSummary_ColumnValue_Header {
            get {
                return ResourceManager.GetString("TokenRewardsSummary_ColumnValue_Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to In all the cases in the table below your account will be credited with tokens..
        /// </summary>
        public static string TokenRewardsSummary_EarnGroup_Description {
            get {
                return ResourceManager.GetString("TokenRewardsSummary_EarnGroup_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You currently earn two times more tokens!.
        /// </summary>
        public static string TokenRewardsSummary_EarnGroup_Footer_DoubleTokens {
            get {
                return ResourceManager.GetString("TokenRewardsSummary_EarnGroup_Footer_DoubleTokens", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You currently earn three times more tokens!.
        /// </summary>
        public static string TokenRewardsSummary_EarnGroup_Footer_TripleTokens {
            get {
                return ResourceManager.GetString("TokenRewardsSummary_EarnGroup_Footer_TripleTokens", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Earn Tokens.
        /// </summary>
        public static string TokenRewardsSummary_EarnGroup_Header {
            get {
                return ResourceManager.GetString("TokenRewardsSummary_EarnGroup_Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Token Rewards.
        /// </summary>
        public static string TokenRewardsSummary_Header {
            get {
                return ResourceManager.GetString("TokenRewardsSummary_Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to In all the cases in the table below you account will be debited with tokens..
        /// </summary>
        public static string TokenRewardsSummary_SpendGroup_Description {
            get {
                return ResourceManager.GetString("TokenRewardsSummary_SpendGroup_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Spend Tokens.
        /// </summary>
        public static string TokenRewardsSummary_SpendGroup_Header {
            get {
                return ResourceManager.GetString("TokenRewardsSummary_SpendGroup_Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to My Token Transactions.
        /// </summary>
        public static string Transactions_PageTitle {
            get {
                return ResourceManager.GetString("Transactions_PageTitle", resourceCulture);
            }
        }
    }
}
