//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Epsilon.Resources.Common {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class CommonResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal CommonResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Epsilon.Resources.Common.CommonResources", typeof(CommonResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Back.
        /// </summary>
        public static string BackLinkText {
            get {
                return ResourceManager.GetString("BackLinkText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Access to the requested content has been disallowed..
        /// </summary>
        public static string ContentAccessDisallowedMessage {
            get {
                return ResourceManager.GetString("ContentAccessDisallowedMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Country.
        /// </summary>
        public static string Country {
            get {
                return ResourceManager.GetString("Country", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FAQ.
        /// </summary>
        public static string Faq_Acronym {
            get {
                return ResourceManager.GetString("Faq_Acronym", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Frequently Asked Questions.
        /// </summary>
        public static string Faq_InFull {
            get {
                return ResourceManager.GetString("Faq_InFull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error occurred while processing your request..
        /// </summary>
        public static string GenericErrorMessage {
            get {
                return ResourceManager.GetString("GenericErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sorry, this action is not valid..
        /// </summary>
        public static string GenericInvalidActionMessage {
            get {
                return ResourceManager.GetString("GenericInvalidActionMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sorry, there was something wrong with your request..
        /// </summary>
        public static string GenericInvalidRequestMessage {
            get {
                return ResourceManager.GetString("GenericInvalidRequestMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Language.
        /// </summary>
        public static string Language {
            get {
                return ResourceManager.GetString("Language", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Login.
        /// </summary>
        public static string Login {
            get {
                return ResourceManager.GetString("Login", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Log off.
        /// </summary>
        public static string LogOff {
            get {
                return ResourceManager.GetString("LogOff", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No.
        /// </summary>
        public static string No {
            get {
                return ResourceManager.GetString("No", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Register.
        /// </summary>
        public static string Register {
            get {
                return ResourceManager.GetString("Register", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Our service is not  available in your country yet. (or possibly we couldn&apos;t determine your country from your IP address).
        /// </summary>
        public static string ServiceNotAvailableInYourCountryMessage {
            get {
                return ResourceManager.GetString("ServiceNotAvailableInYourCountryMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Poor.
        /// </summary>
        public static string StarRating_1_Title {
            get {
                return ResourceManager.GetString("StarRating_1_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fair.
        /// </summary>
        public static string StarRating_2_Title {
            get {
                return ResourceManager.GetString("StarRating_2_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Average.
        /// </summary>
        public static string StarRating_3_Title {
            get {
                return ResourceManager.GetString("StarRating_3_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Good.
        /// </summary>
        public static string StarRating_4_Title {
            get {
                return ResourceManager.GetString("StarRating_4_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Excellent.
        /// </summary>
        public static string StarRating_5_Title {
            get {
                return ResourceManager.GetString("StarRating_5_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Step 1.
        /// </summary>
        public static string Step1 {
            get {
                return ResourceManager.GetString("Step1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Step 2.
        /// </summary>
        public static string Step2 {
            get {
                return ResourceManager.GetString("Step2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The {0} must be at least {2} characters long..
        /// </summary>
        public static string StringLengthErrorMessage {
            get {
                return ResourceManager.GetString("StringLengthErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This is the balance of tokens currently in your account..
        /// </summary>
        public static string TokenBalanceBadgeHoverText {
            get {
                return ResourceManager.GetString("TokenBalanceBadgeHoverText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The language selected is not supported yet..
        /// </summary>
        public static string UnsupportedLanguageMessage {
            get {
                return ResourceManager.GetString("UnsupportedLanguageMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to We are performing site maintenance work. We will be back shortly..
        /// </summary>
        public static string WebsiteDisabledForMaintenanceMessage {
            get {
                return ResourceManager.GetString("WebsiteDisabledForMaintenanceMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to We are experiencing some technical issues. We are working on it! Come back shortly..
        /// </summary>
        public static string WebsiteDownMessage {
            get {
                return ResourceManager.GetString("WebsiteDownMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yes.
        /// </summary>
        public static string Yes {
            get {
                return ResourceManager.GetString("Yes", resourceCulture);
            }
        }
    }
}
