//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Epsilon.Resources.Web.OutgoingVerification {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class OutgoingVerificationResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal OutgoingVerificationResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Epsilon.Resources.Web.OutgoingVerification.OutgoingVerificationResources", typeof(OutgoingVerificationResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mark outgoing verification as sent?.
        /// </summary>
        public static string MyOutgoingVerificationsSummary_ActionMarkAsSent_ButtonConfirmationText {
            get {
                return ResourceManager.GetString("MyOutgoingVerificationsSummary_ActionMarkAsSent_ButtonConfirmationText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Marks the outgoing verification as sent..
        /// </summary>
        public static string MyOutgoingVerificationsSummary_ActionMarkAsSent_ButtonHoverText {
            get {
                return ResourceManager.GetString("MyOutgoingVerificationsSummary_ActionMarkAsSent_ButtonHoverText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mark Sent.
        /// </summary>
        public static string MyOutgoingVerificationsSummary_ActionMarkAsSent_ButtonText {
            get {
                return ResourceManager.GetString("MyOutgoingVerificationsSummary_ActionMarkAsSent_ButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Actions.
        /// </summary>
        public static string MyOutgoingVerificationsSummary_ActionsColumnHeader {
            get {
                return ResourceManager.GetString("MyOutgoingVerificationsSummary_ActionsColumnHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Address Area.
        /// </summary>
        public static string MyOutgoingVerificationsSummary_AddressAreaColumnHeader {
            get {
                return ResourceManager.GetString("MyOutgoingVerificationsSummary_AddressAreaColumnHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to My Outgoing Verifications.
        /// </summary>
        public static string MyOutgoingVerificationsSummary_Header {
            get {
                return ResourceManager.GetString("MyOutgoingVerificationsSummary_Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Verification Id.
        /// </summary>
        public static string MyOutgoingVerificationsSummary_IdColumnHeader {
            get {
                return ResourceManager.GetString("MyOutgoingVerificationsSummary_IdColumnHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to My Outgoing Verifications.
        /// </summary>
        public static string MyOutgoingVerificationsSummary_PageTitle {
            get {
                return ResourceManager.GetString("MyOutgoingVerificationsSummary_PageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Progress.
        /// </summary>
        public static string MyOutgoingVerificationsSummary_ProgressColumnHeader {
            get {
                return ResourceManager.GetString("MyOutgoingVerificationsSummary_ProgressColumnHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This verification has been received..
        /// </summary>
        public static string MyOutgoingVerificationsSummary_StepVerificationReceivedDone_IconHoverText {
            get {
                return ResourceManager.GetString("MyOutgoingVerificationsSummary_StepVerificationReceivedDone_IconHoverText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You have marked this verification as sent..
        /// </summary>
        public static string MyOutgoingVerificationsSummary_StepVerificationSentOutDone_IconHoverText {
            get {
                return ResourceManager.GetString("MyOutgoingVerificationsSummary_StepVerificationSentOutDone_IconHoverText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to View all outgoing verifications.
        /// </summary>
        public static string MyOutgoingVerificationsSummary_ViewAllLinkText {
            get {
                return ResourceManager.GetString("MyOutgoingVerificationsSummary_ViewAllLinkText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to My Latest Outgoing Verifications.
        /// </summary>
        public static string MyOutgoingVerificationsSummary_WithLimit_Header {
            get {
                return ResourceManager.GetString("MyOutgoingVerificationsSummary_WithLimit_Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You will be assigned to send a verification mail by post to verify another user..
        /// </summary>
        public static string Pick_ConfirmationText {
            get {
                return ResourceManager.GetString("Pick_ConfirmationText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New Outgoing Verification.
        /// </summary>
        public static string Pick_Header {
            get {
                return ResourceManager.GetString("Pick_Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New Outgoing Verification.
        /// </summary>
        public static string Pick_PageTitle {
            get {
                return ResourceManager.GetString("Pick_PageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Proceed.
        /// </summary>
        public static string Pick_SubmitButton {
            get {
                return ResourceManager.GetString("Pick_SubmitButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string String1 {
            get {
                return ResourceManager.GetString("String1", resourceCulture);
            }
        }
    }
}
