//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Epsilon.Resources.Web.Home {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class HomeResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal HomeResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Epsilon.Resources.Web.Home.HomeResources", typeof(HomeResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to   .
        /// </summary>
        public static string Index_Header {
            get {
                return ResourceManager.GetString("Index_Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to How it works.
        /// </summary>
        public static string Index_HowItWorks_Header {
            get {
                return ResourceManager.GetString("Index_HowItWorks_Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You use the codes to verify your address. You earn tokens..
        /// </summary>
        public static string Index_HowItWorks_StepEnterVerificationCode_Text {
            get {
                return ResourceManager.GetString("Index_HowItWorks_StepEnterVerificationCode_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to To earn more tokens, you can help by sending verification codes by post to other users..
        /// </summary>
        public static string Index_HowItWorks_StepHelpSendVerifications_Text {
            get {
                return ResourceManager.GetString("Index_HowItWorks_StepHelpSendVerifications_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You pick or add your address. We don&apos;t store your name, just your address..
        /// </summary>
        public static string Index_HowItWorks_StepPickAddAddress_Text {
            get {
                return ResourceManager.GetString("Index_HowItWorks_StepPickAddAddress_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You receive two verification codes by post..
        /// </summary>
        public static string Index_HowItWorks_StepReceiveVerification_Text {
            get {
                return ResourceManager.GetString("Index_HowItWorks_StepReceiveVerification_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You can use your tokens to access information for other properties..
        /// </summary>
        public static string Index_HowItWorks_StepSpendTokens_Text {
            get {
                return ResourceManager.GetString("Index_HowItWorks_StepSpendTokens_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Once verified, you can submit the details for your tenancy. You earn more tokens..
        /// </summary>
        public static string Index_HowItWorks_StepSubmitTenancyDetails_Text {
            get {
                return ResourceManager.GetString("Index_HowItWorks_StepSubmitTenancyDetails_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Our mission is to bring transparency to historic house rental prices..
        /// </summary>
        public static string Index_MissionStatement_OpeningLine {
            get {
                return ResourceManager.GetString("Index_MissionStatement_OpeningLine", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to We have created a platform that enables tenants to voluntarily share information. Tenants are verified by post in a peer-to-peer fashion by other users..
        /// </summary>
        public static string Index_MissionStatement_Rest {
            get {
                return ResourceManager.GetString("Index_MissionStatement_Rest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Welcome.
        /// </summary>
        public static string Index_PageTitle {
            get {
                return ResourceManager.GetString("Index_PageTitle", resourceCulture);
            }
        }
    }
}
