CREATE VIEW [dbo].[ResponseTimingStatistics]
AS
SELECT [ControllerName] 
     , [ActionName]
     , [HttpVerb]
     , [IsApi]
     , MIN([TimeInMilliseconds]) AS [Minimum]
     , AVG([TimeInMilliseconds]) AS [Average]
     , MAX([TimeInMilliseconds]) AS [Maximum]
FROM [dbo].[ResponseTiming]
GROUP BY [ControllerName], [ActionName], [HttpVerb], [IsApi]