//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Epsilon.Resources.Logic.TokenRewardKey {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class TokenRewardKeyResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal TokenRewardKeyResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Epsilon.Resources.Logic.TokenRewardKey.TokenRewardKeyResources", typeof(TokenRewardKeyResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tokens earned by the tenant when the tenancy information are submitted..
        /// </summary>
        public static string EarnPerTenancyDetailsSubmission_Description {
            get {
                return ResourceManager.GetString("EarnPerTenancyDetailsSubmission_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tenancy Details Submitted.
        /// </summary>
        public static string EarnPerTenancyDetailsSubmission_DisplayName {
            get {
                return ResourceManager.GetString("EarnPerTenancyDetailsSubmission_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tokens earned by the recepient of a verification code when the code is used..
        /// </summary>
        public static string EarnPerVerificationCodeEntered_Description {
            get {
                return ResourceManager.GetString("EarnPerVerificationCodeEntered_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Verification Code Entered.
        /// </summary>
        public static string EarnPerVerificationCodeEntered_DisplayName {
            get {
                return ResourceManager.GetString("EarnPerVerificationCodeEntered_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tokens earned by the sender of a verification code when the recipient uses the code..
        /// </summary>
        public static string EarnPerVerificationMailSent_Description {
            get {
                return ResourceManager.GetString("EarnPerVerificationMailSent_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Outgoing Verification Sent.
        /// </summary>
        public static string EarnPerVerificationMailSent_DisplayName {
            get {
                return ResourceManager.GetString("EarnPerVerificationMailSent_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tokens spent when accessing the information for a property..
        /// </summary>
        public static string SpendPerPropertyInfoAccess_Description {
            get {
                return ResourceManager.GetString("SpendPerPropertyInfoAccess_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Access Property Information.
        /// </summary>
        public static string SpendPerPropertyInfoAccess_DisplayName {
            get {
                return ResourceManager.GetString("SpendPerPropertyInfoAccess_DisplayName", resourceCulture);
            }
        }
    }
}
