namespace Epsilon.Logic.Constants.Enums
{
    public enum CountryVariantResourceName
    { 
        Address_Line1,
        Address_Line1_MaxLengthValidationMessage,
        Address_Line2,
        Address_Line2_MaxLengthValidationMessage,
        Address_Line3,
        Address_Line3_MaxLengthValidationMessage,
        Address_Line4,
        Address_Line4_MaxLengthValidationMessage,
        Address_Locality,
        Address_Locality_MaxLengthValidationMessage,
        Address_Region,
        Address_Region_MaxLengthValidationMessage,
        Address_Postcode,
        Address_Postcode_MaxLengthValidationMessage,
        OutgoingVerificationInstructions_AddressChecker_DisplayName,
        OutgoingVerificationInstructions_AddressChecker_Url,
        OutgoingVerificationInstructions_SendPaperMailOnlineProvider_1_DisplayName,
        OutgoingVerificationInstructions_SendPaperMailOnlineProvider_1_Url,
        OutgoingVerificationInstructions_SendPaperMailOnlineProvider_2_DisplayName,
        OutgoingVerificationInstructions_SendPaperMailOnlineProvider_2_Url,
        SearchAddress_PostcodePlaceholder,
        SearchAddress_TermsPlaceholder,
        SearchProperty_PostcodePlaceholder,
        SearchProperty_TermsPlaceholder
    }
}
