//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Epsilon.Resources.Web.UserHome {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class UserHomeResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal UserHomeResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Epsilon.Resources.Web.UserHome.UserHomeResources", typeof(UserHomeResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User Home Page.
        /// </summary>
        public static string Index_PageTitle {
            get {
                return ResourceManager.GetString("Index_PageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start.
        /// </summary>
        public static string SectionCreateSubmission_ButtonText {
            get {
                return ResourceManager.GetString("SectionCreateSubmission_ButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start.
        /// </summary>
        public static string SectionCreateSubmission_Header {
            get {
                return ResourceManager.GetString("SectionCreateSubmission_Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start by providing your address details..
        /// </summary>
        public static string SectionCreateSubmission_Text {
            get {
                return ResourceManager.GetString("SectionCreateSubmission_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Explore.
        /// </summary>
        public static string SectionExploreProperties_ButtonText {
            get {
                return ResourceManager.GetString("SectionExploreProperties_ButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Explore.
        /// </summary>
        public static string SectionExploreProperties_Header {
            get {
                return ResourceManager.GetString("SectionExploreProperties_Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Explore properties..
        /// </summary>
        public static string SectionExploreProperties_Text {
            get {
                return ResourceManager.GetString("SectionExploreProperties_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Help.
        /// </summary>
        public static string SectionPickOutgoingVerification_ButtonText {
            get {
                return ResourceManager.GetString("SectionPickOutgoingVerification_ButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Help.
        /// </summary>
        public static string SectionPickOutgoingVerification_Header {
            get {
                return ResourceManager.GetString("SectionPickOutgoingVerification_Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Help by sending verification mail to other users. Earn tokens..
        /// </summary>
        public static string SectionPickOutgoingVerification_Text {
            get {
                return ResourceManager.GetString("SectionPickOutgoingVerification_Text", resourceCulture);
            }
        }
    }
}
