//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Epsilon.Resources.Logic.TenancyDetailsSubmission
{


    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class TenancyDetailsSubmissionResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal TenancyDetailsSubmissionResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Epsilon.Resources.Logic.TenancyDetailsSubmission.TenancyDetailsSubmissionResource" +
                            "s", typeof(TenancyDetailsSubmissionResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The address was not found in our system..
        /// </summary>
        public static string Create_AddressNotFoundMessage {
            get {
                return ResourceManager.GetString("Create_AddressNotFoundMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There has been a recent submission for this address. Please try again in a few weeks..
        /// </summary>
        public static string Create_MaxFrequencyPerAddressCheck_RejectionMessage {
            get {
                return ResourceManager.GetString("Create_MaxFrequencyPerAddressCheck_RejectionMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your submission has been initiated. You will receive a verification code by post soon..
        /// </summary>
        public static string Create_SuccessMessage {
            get {
                return ResourceManager.GetString("Create_SuccessMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The verification code is not valid..
        /// </summary>
        public static string EnterVerification_InvalidVerificationCode_RejectionMessage {
            get {
                return ResourceManager.GetString("EnterVerification_InvalidVerificationCode_RejectionMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The verification code has already been used..
        /// </summary>
        public static string EnterVerification_VerificationAlreadyUsed_RejectionMessage {
            get {
                return ResourceManager.GetString("EnterVerification_VerificationAlreadyUsed_RejectionMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The code has been accepted..
        /// </summary>
        public static string EnterVerificationCode_SuccessMessage {
            get {
                return ResourceManager.GetString("EnterVerificationCode_SuccessMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Creating a new submission is temporarily disabled. Please try again later..
        /// </summary>
        public static string GlobalSwitch_CreateTenancyDetailsSubmissionDisabled_Message {
            get {
                return ResourceManager.GetString("GlobalSwitch_CreateTenancyDetailsSubmissionDisabled_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thanks you! The details have been submitted successfully..
        /// </summary>
        public static string SubmitTenancyDetails_SuccessMessage {
            get {
                return ResourceManager.GetString("SubmitTenancyDetails_SuccessMessage", resourceCulture);
            }
        }
    }
}
