//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Epsilon.Resources.CountryVariants {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class ResourcesGR {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ResourcesGR() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Epsilon.Resources.CountryVariants.ResourcesGR", typeof(ResourcesGR).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Street and Number.
        /// </summary>
        public static string Address_Line1 {
            get {
                return ResourceManager.GetString("Address_Line1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Street and Number field must be a string with a maximum length of {0}..
        /// </summary>
        public static string Address_Line1_MaxLengthValidationMessage {
            get {
                return ResourceManager.GetString("Address_Line1_MaxLengthValidationMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string Address_Line2 {
            get {
                return ResourceManager.GetString("Address_Line2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string Address_Line2_MaxLengthValidationMessage {
            get {
                return ResourceManager.GetString("Address_Line2_MaxLengthValidationMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string Address_Line3 {
            get {
                return ResourceManager.GetString("Address_Line3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string Address_Line3_MaxLengthValidationMessage {
            get {
                return ResourceManager.GetString("Address_Line3_MaxLengthValidationMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string Address_Line4 {
            get {
                return ResourceManager.GetString("Address_Line4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string Address_Line4_MaxLengthValidationMessage {
            get {
                return ResourceManager.GetString("Address_Line4_MaxLengthValidationMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Town/City.
        /// </summary>
        public static string Address_Locality {
            get {
                return ResourceManager.GetString("Address_Locality", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Town/City field must be a string with a maximum length of {0}..
        /// </summary>
        public static string Address_Locality_MaxLengthValidationMessage {
            get {
                return ResourceManager.GetString("Address_Locality_MaxLengthValidationMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Postal Code.
        /// </summary>
        public static string Address_Postcode {
            get {
                return ResourceManager.GetString("Address_Postcode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Postal Code field must be a string with a maximum length of {0}..
        /// </summary>
        public static string Address_Postcode_MaxLengthValidationMessage {
            get {
                return ResourceManager.GetString("Address_Postcode_MaxLengthValidationMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Prefecture.
        /// </summary>
        public static string Address_Region {
            get {
                return ResourceManager.GetString("Address_Region", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Prefecture field must be a string with a maximum length of {0}..
        /// </summary>
        public static string Address_Region_MaxLengthValidationMessage {
            get {
                return ResourceManager.GetString("Address_Region_MaxLengthValidationMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to exact postal code.
        /// </summary>
        public static string SearchAddress_PostcodePlaceholder {
            get {
                return ResourceManager.GetString("SearchAddress_PostcodePlaceholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to street number or any part of address.
        /// </summary>
        public static string SearchAddress_TermsPlaceholder {
            get {
                return ResourceManager.GetString("SearchAddress_TermsPlaceholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to exact postal code.
        /// </summary>
        public static string SearchProperty_PostcodePlaceholder {
            get {
                return ResourceManager.GetString("SearchProperty_PostcodePlaceholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to street number or any part of address.
        /// </summary>
        public static string SearchProperty_TermsPlaceholder {
            get {
                return ResourceManager.GetString("SearchProperty_TermsPlaceholder", resourceCulture);
            }
        }
    }
}
