//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Epsilon.Resources.CountryVariants
{


    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class ResourcesGB {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ResourcesGB() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Epsilon.Resources.CountryVariants.ResourcesGB", typeof(ResourcesGB).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Property Number and Bulding Name.
        /// </summary>
        public static string Address_Line1 {
            get {
                return ResourceManager.GetString("Address_Line1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Property Number and Bulding Name field must be a string with a maximum length of {0}..
        /// </summary>
        public static string Address_Line1_MaxLengthValidationMessage {
            get {
                return ResourceManager.GetString("Address_Line1_MaxLengthValidationMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Building Number and Street.
        /// </summary>
        public static string Address_Line2 {
            get {
                return ResourceManager.GetString("Address_Line2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Building Number and Street field must be a string with a maximum length of {0}..
        /// </summary>
        public static string Address_Line2_MaxLengthValidationMessage {
            get {
                return ResourceManager.GetString("Address_Line2_MaxLengthValidationMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string Address_Line3 {
            get {
                return ResourceManager.GetString("Address_Line3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string Address_Line3_MaxLengthValidationMessage {
            get {
                return ResourceManager.GetString("Address_Line3_MaxLengthValidationMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string Address_Line4 {
            get {
                return ResourceManager.GetString("Address_Line4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string Address_Line4_MaxLengthValidationMessage {
            get {
                return ResourceManager.GetString("Address_Line4_MaxLengthValidationMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Town/City.
        /// </summary>
        public static string Address_Locality {
            get {
                return ResourceManager.GetString("Address_Locality", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Town/City field must be a string with a maximum length of {0}..
        /// </summary>
        public static string Address_Locality_MaxLengthValidationMessage {
            get {
                return ResourceManager.GetString("Address_Locality_MaxLengthValidationMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Postcode.
        /// </summary>
        public static string Address_Postcode {
            get {
                return ResourceManager.GetString("Address_Postcode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Postcode field must be a string with a maximum length of {0}..
        /// </summary>
        public static string Address_Postcode_MaxLengthValidationMessage {
            get {
                return ResourceManager.GetString("Address_Postcode_MaxLengthValidationMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to County.
        /// </summary>
        public static string Address_Region {
            get {
                return ResourceManager.GetString("Address_Region", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The County field must be a string with a maximum length of {0}..
        /// </summary>
        public static string Address_Region_MaxLengthValidationMessage {
            get {
                return ResourceManager.GetString("Address_Region_MaxLengthValidationMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PostOffice: Find a postcode or address.
        /// </summary>
        public static string OutgoingVerificationInstructions_AddressChecker_DisplayName {
            get {
                return ResourceManager.GetString("OutgoingVerificationInstructions_AddressChecker_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to http://www.postoffice.co.uk/postcode-finder.
        /// </summary>
        public static string OutgoingVerificationInstructions_AddressChecker_Url {
            get {
                return ResourceManager.GetString("OutgoingVerificationInstructions_AddressChecker_Url", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PC2Paper.
        /// </summary>
        public static string OutgoingVerificationInstructions_SendPaperMailOnlineProvider_1_DisplayName {
            get {
                return ResourceManager.GetString("OutgoingVerificationInstructions_SendPaperMailOnlineProvider_1_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to http://www.pc2paper.co.uk.
        /// </summary>
        public static string OutgoingVerificationInstructions_SendPaperMailOnlineProvider_1_Url {
            get {
                return ResourceManager.GetString("OutgoingVerificationInstructions_SendPaperMailOnlineProvider_1_Url", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to L-Mail.
        /// </summary>
        public static string OutgoingVerificationInstructions_SendPaperMailOnlineProvider_2_DisplayName {
            get {
                return ResourceManager.GetString("OutgoingVerificationInstructions_SendPaperMailOnlineProvider_2_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to http://www.l-mail.com.
        /// </summary>
        public static string OutgoingVerificationInstructions_SendPaperMailOnlineProvider_2_Url {
            get {
                return ResourceManager.GetString("OutgoingVerificationInstructions_SendPaperMailOnlineProvider_2_Url", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to exact postcode.
        /// </summary>
        public static string SearchAddress_PostcodePlaceholder {
            get {
                return ResourceManager.GetString("SearchAddress_PostcodePlaceholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to property number or any part of address.
        /// </summary>
        public static string SearchAddress_TermsPlaceholder {
            get {
                return ResourceManager.GetString("SearchAddress_TermsPlaceholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to exact postcode.
        /// </summary>
        public static string SearchProperty_PostcodePlaceholder {
            get {
                return ResourceManager.GetString("SearchProperty_PostcodePlaceholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to property number or any part of address.
        /// </summary>
        public static string SearchProperty_TermsPlaceholder {
            get {
                return ResourceManager.GetString("SearchProperty_TermsPlaceholder", resourceCulture);
            }
        }
    }
}
