//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Epsilon.Resources.Web.Submission {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class SubmissionResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal SubmissionResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Epsilon.Resources.Web.Submission.SubmissionResources", typeof(SubmissionResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Back to search.
        /// </summary>
        public static string AddAddress_BackToSearchLink {
            get {
                return ResourceManager.GetString("AddAddress_BackToSearchLink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please double check and confirm that all address details are correct. You won&apos;t be able to correct them after this step, while each user is allowed to add a limited number of addresses..
        /// </summary>
        public static string AddAddress_ConfirmationText {
            get {
                return ResourceManager.GetString("AddAddress_ConfirmationText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add your address.
        /// </summary>
        public static string AddAddress_PageHeader {
            get {
                return ResourceManager.GetString("AddAddress_PageHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add your address.
        /// </summary>
        public static string AddAddress_PageTitle {
            get {
                return ResourceManager.GetString("AddAddress_PageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Submit.
        /// </summary>
        public static string AddAddress_SubmitButton {
            get {
                return ResourceManager.GetString("AddAddress_SubmitButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter Verification Code.
        /// </summary>
        public static string EnterVerificationCode_PageHeader {
            get {
                return ResourceManager.GetString("EnterVerificationCode_PageHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter Verification Code.
        /// </summary>
        public static string EnterVerificationCode_PageTitle {
            get {
                return ResourceManager.GetString("EnterVerificationCode_PageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Submit.
        /// </summary>
        public static string EnterVerificationCode_SubmitButtonText {
            get {
                return ResourceManager.GetString("EnterVerificationCode_SubmitButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Move-Out Date.
        /// </summary>
        public static string MoveOutDetailsForm_FieldMoveOutDate_DisplayName {
            get {
                return ResourceManager.GetString("MoveOutDetailsForm_FieldMoveOutDate_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Move-Out Date field is required..
        /// </summary>
        public static string MoveOutDetailsForm_FieldMoveOutDate_RequiredErrorMessage {
            get {
                return ResourceManager.GetString("MoveOutDetailsForm_FieldMoveOutDate_RequiredErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter verification code received by post..
        /// </summary>
        public static string MySubmissionsSummary_ActionEnterVerificationCode_ButtonHoverText {
            get {
                return ResourceManager.GetString("MySubmissionsSummary_ActionEnterVerificationCode_ButtonHoverText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter Code.
        /// </summary>
        public static string MySubmissionsSummary_ActionEnterVerificationCode_ButtonText {
            get {
                return ResourceManager.GetString("MySubmissionsSummary_ActionEnterVerificationCode_ButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Actions.
        /// </summary>
        public static string MySubmissionsSummary_ActionsColumnHeader {
            get {
                return ResourceManager.GetString("MySubmissionsSummary_ActionsColumnHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Submit the move-out date for this tenancy..
        /// </summary>
        public static string MySubmissionsSummary_ActionSubmitMoveOutDetails_ButtonHoverText {
            get {
                return ResourceManager.GetString("MySubmissionsSummary_ActionSubmitMoveOutDetails_ButtonHoverText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Moved Out.
        /// </summary>
        public static string MySubmissionsSummary_ActionSubmitMoveOutDetails_ButtonText {
            get {
                return ResourceManager.GetString("MySubmissionsSummary_ActionSubmitMoveOutDetails_ButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Submit rent and other details for this tenancy..
        /// </summary>
        public static string MySubmissionsSummary_ActionSubmitTenancyDetails_ButtonHoverText {
            get {
                return ResourceManager.GetString("MySubmissionsSummary_ActionSubmitTenancyDetails_ButtonHoverText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Submit Details.
        /// </summary>
        public static string MySubmissionsSummary_ActionSubmitTenancyDetails_ButtonText {
            get {
                return ResourceManager.GetString("MySubmissionsSummary_ActionSubmitTenancyDetails_ButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Address.
        /// </summary>
        public static string MySubmissionsSummary_AddressColumnHeader {
            get {
                return ResourceManager.GetString("MySubmissionsSummary_AddressColumnHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to My Submissions.
        /// </summary>
        public static string MySubmissionsSummary_Header {
            get {
                return ResourceManager.GetString("MySubmissionsSummary_Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to My Submissions.
        /// </summary>
        public static string MySubmissionsSummary_PageTitle {
            get {
                return ResourceManager.GetString("MySubmissionsSummary_PageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Progress.
        /// </summary>
        public static string MySubmissionsSummary_ProgressColumnHeader {
            get {
                return ResourceManager.GetString("MySubmissionsSummary_ProgressColumnHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You have moved out from this address..
        /// </summary>
        public static string MySubmissionsSummary_StepMoveOutDetailsSubmittedDone_IconHoverText {
            get {
                return ResourceManager.GetString("MySubmissionsSummary_StepMoveOutDetailsSubmittedDone_IconHoverText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You have submitted the details for this address..
        /// </summary>
        public static string MySubmissionsSummary_StepTenancyDetailsSubmittedDone_IconHoverText {
            get {
                return ResourceManager.GetString("MySubmissionsSummary_StepTenancyDetailsSubmittedDone_IconHoverText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You have verified this address..
        /// </summary>
        public static string MySubmissionsSummary_StepVerificationCodeEnteredDone_IconHoverText {
            get {
                return ResourceManager.GetString("MySubmissionsSummary_StepVerificationCodeEnteredDone_IconHoverText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A verification code has been sent to this address..
        /// </summary>
        public static string MySubmissionsSummary_StepVerificationCodeSentOutDone_IconHoverText {
            get {
                return ResourceManager.GetString("MySubmissionsSummary_StepVerificationCodeSentOutDone_IconHoverText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to My Latest Submissions.
        /// </summary>
        public static string MySubmissionsSummary_WithLimit_Header {
            get {
                return ResourceManager.GetString("MySubmissionsSummary_WithLimit_Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to View all submissions.
        /// </summary>
        public static string MySubmissionSummary_ViewAllLinkText {
            get {
                return ResourceManager.GetString("MySubmissionSummary_ViewAllLinkText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add new address.
        /// </summary>
        public static string SearchAddress_AddNewAddressButton {
            get {
                return ResourceManager.GetString("SearchAddress_AddNewAddressButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to If your address is not among the results please add it..
        /// </summary>
        public static string SearchAddress_AddYourAddressMessage {
            get {
                return ResourceManager.GetString("SearchAddress_AddYourAddressMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your search returned more than {0} results. If your address is not among them, please narrow down your search..
        /// </summary>
        public static string SearchAddress_NarrowDownYourSearchMessage {
            get {
                return ResourceManager.GetString("SearchAddress_NarrowDownYourSearchMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No addresses found. Please add your address..
        /// </summary>
        public static string SearchAddress_NoAddressesFoundMessage {
            get {
                return ResourceManager.GetString("SearchAddress_NoAddressesFoundMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Find your address.
        /// </summary>
        public static string SearchAddress_PageHeader {
            get {
                return ResourceManager.GetString("SearchAddress_PageHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Find your address.
        /// </summary>
        public static string SearchAddress_PageTitle {
            get {
                return ResourceManager.GetString("SearchAddress_PageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search.
        /// </summary>
        public static string SearchAddress_SearchButton {
            get {
                return ResourceManager.GetString("SearchAddress_SearchButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search terms.
        /// </summary>
        public static string SearchAddress_SearchTermsLabel {
            get {
                return ResourceManager.GetString("SearchAddress_SearchTermsLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select your address among the results to continue..
        /// </summary>
        public static string SearchAddress_SelectYourAddressMessage {
            get {
                return ResourceManager.GetString("SearchAddress_SelectYourAddressMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Use Selected Address.
        /// </summary>
        public static string SearchAddress_UseSelectedAddressButton {
            get {
                return ResourceManager.GetString("SearchAddress_UseSelectedAddressButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The information above is correct..
        /// </summary>
        public static string SubmitMoveOutDetails_ConfirmationText {
            get {
                return ResourceManager.GetString("SubmitMoveOutDetails_ConfirmationText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Submit Move-Out Details.
        /// </summary>
        public static string SubmitMoveOutDetails_PageHeader {
            get {
                return ResourceManager.GetString("SubmitMoveOutDetails_PageHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Submit Move-Out Details.
        /// </summary>
        public static string SubmitMoveOutDetails_PageTitle {
            get {
                return ResourceManager.GetString("SubmitMoveOutDetails_PageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Submit.
        /// </summary>
        public static string SubmitMoveOutDetails_SubmitButtonText {
            get {
                return ResourceManager.GetString("SubmitMoveOutDetails_SubmitButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The information above is correct..
        /// </summary>
        public static string SubmitTenancyDetails_ConfirmationText {
            get {
                return ResourceManager.GetString("SubmitTenancyDetails_ConfirmationText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Submit Details.
        /// </summary>
        public static string SubmitTenancyDetails_PageHeader {
            get {
                return ResourceManager.GetString("SubmitTenancyDetails_PageHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Submit Details.
        /// </summary>
        public static string SubmitTenancyDetails_PageTitle {
            get {
                return ResourceManager.GetString("SubmitTenancyDetails_PageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Submit.
        /// </summary>
        public static string SubmitTenancyDetails_SubmitButtonText {
            get {
                return ResourceManager.GetString("SubmitTenancyDetails_SubmitButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Renting Part of the Property?.
        /// </summary>
        public static string SubmitTenancyDetailsForm_FieldIsPartOfProperty_DisplayName {
            get {
                return ResourceManager.GetString("SubmitTenancyDetailsForm_FieldIsPartOfProperty_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Renting Part of the Property field is Required..
        /// </summary>
        public static string SubmitTenancyDetailsForm_FieldIsPartOfProperty_RequiredErrorMessage {
            get {
                return ResourceManager.GetString("SubmitTenancyDetailsForm_FieldIsPartOfProperty_RequiredErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Move-In Date.
        /// </summary>
        public static string SubmitTenancyDetailsForm_FieldMoveInDate_DisplayName {
            get {
                return ResourceManager.GetString("SubmitTenancyDetailsForm_FieldMoveInDate_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Move-In Date field is required..
        /// </summary>
        public static string SubmitTenancyDetailsForm_FieldMoveInDate_RequiredErrorMessage {
            get {
                return ResourceManager.GetString("SubmitTenancyDetailsForm_FieldMoveInDate_RequiredErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total Number of Bedrooms.
        /// </summary>
        public static string SubmitTenancyDetailsForm_FieldNumberOfBedrooms_DisplayName {
            get {
                return ResourceManager.GetString("SubmitTenancyDetailsForm_FieldNumberOfBedrooms_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Total Number of Bedrooms fields must be between 0 and 20..
        /// </summary>
        public static string SubmitTenancyDetailsForm_FieldNumberOfBedrooms_RangeErrorMessage {
            get {
                return ResourceManager.GetString("SubmitTenancyDetailsForm_FieldNumberOfBedrooms_RangeErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Total Number of Bedrooms field is required..
        /// </summary>
        public static string SubmitTenancyDetailsForm_FieldNumberOfBedrooms_RequiredErrorMessage {
            get {
                return ResourceManager.GetString("SubmitTenancyDetailsForm_FieldNumberOfBedrooms_RequiredErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rent.
        /// </summary>
        public static string SubmitTenancyDetailsForm_FieldRent_DisplayName {
            get {
                return ResourceManager.GetString("SubmitTenancyDetailsForm_FieldRent_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Rent field must be positive..
        /// </summary>
        public static string SubmitTenancyDetailsForm_FieldRent_RangeErrorMessage {
            get {
                return ResourceManager.GetString("SubmitTenancyDetailsForm_FieldRent_RangeErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Rent field is required..
        /// </summary>
        public static string SubmitTenancyDetailsForm_FieldRent_RequiredErrorMessage {
            get {
                return ResourceManager.GetString("SubmitTenancyDetailsForm_FieldRent_RequiredErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to I confirm this is my address..
        /// </summary>
        public static string UseAddress_ConfirmationText {
            get {
                return ResourceManager.GetString("UseAddress_ConfirmationText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirm your address.
        /// </summary>
        public static string UseAddress_PageHeader {
            get {
                return ResourceManager.GetString("UseAddress_PageHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirm your address.
        /// </summary>
        public static string UseAddress_PageTitle {
            get {
                return ResourceManager.GetString("UseAddress_PageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirm.
        /// </summary>
        public static string UseAddress_SubmitButtonText {
            get {
                return ResourceManager.GetString("UseAddress_SubmitButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The address was not found in our system..
        /// </summary>
        public static string UseAddressConfirmed_AddressNotFoundMessage {
            get {
                return ResourceManager.GetString("UseAddressConfirmed_AddressNotFoundMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Verification Code.
        /// </summary>
        public static string VerificationCodeForm_FieldVerificationCode_DisplayName {
            get {
                return ResourceManager.GetString("VerificationCodeForm_FieldVerificationCode_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Verification Code field is required..
        /// </summary>
        public static string VerificationCodeForm_FieldVerificationCode_RequiredErrorMessage {
            get {
                return ResourceManager.GetString("VerificationCodeForm_FieldVerificationCode_RequiredErrorMessage", resourceCulture);
            }
        }
    }
}
