//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.0
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Epsilon.Resources.Web.Submission {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class SubmissionResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal SubmissionResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Epsilon.Resources.Web.Submission.SubmissionResources", typeof(SubmissionResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Back to search.
        /// </summary>
        public static string AddAddress_BackToSearchLink {
            get {
                return ResourceManager.GetString("AddAddress_BackToSearchLink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please double check and confirm that all address details are correct. You won&apos;t be able to correct them after this step, while each user is allowed to add a limited number of addresses..
        /// </summary>
        public static string AddAddress_ConfirmationText {
            get {
                return ResourceManager.GetString("AddAddress_ConfirmationText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add your address.
        /// </summary>
        public static string AddAddress_PageHeader {
            get {
                return ResourceManager.GetString("AddAddress_PageHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add your address.
        /// </summary>
        public static string AddAddress_PageTitle {
            get {
                return ResourceManager.GetString("AddAddress_PageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Submit.
        /// </summary>
        public static string AddAddress_SubmitButton {
            get {
                return ResourceManager.GetString("AddAddress_SubmitButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add new address.
        /// </summary>
        public static string SearchAddress_AddNewAddressButton {
            get {
                return ResourceManager.GetString("SearchAddress_AddNewAddressButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to If your address is not among the results please add it..
        /// </summary>
        public static string SearchAddress_AddYourAddressMessage {
            get {
                return ResourceManager.GetString("SearchAddress_AddYourAddressMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your search returned more than {0} results. If your address is not among them, please narrow down your search..
        /// </summary>
        public static string SearchAddress_NarrowDownYourSearchMessage {
            get {
                return ResourceManager.GetString("SearchAddress_NarrowDownYourSearchMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No addresses found. Please add your address..
        /// </summary>
        public static string SearchAddress_NoAddressesFoundMessage {
            get {
                return ResourceManager.GetString("SearchAddress_NoAddressesFoundMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Find your address.
        /// </summary>
        public static string SearchAddress_PageHeader {
            get {
                return ResourceManager.GetString("SearchAddress_PageHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Find your address.
        /// </summary>
        public static string SearchAddress_PageTitle {
            get {
                return ResourceManager.GetString("SearchAddress_PageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search.
        /// </summary>
        public static string SearchAddress_SearchButton {
            get {
                return ResourceManager.GetString("SearchAddress_SearchButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search terms.
        /// </summary>
        public static string SearchAddress_SearchTermsLabel {
            get {
                return ResourceManager.GetString("SearchAddress_SearchTermsLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select your address among the results to continue..
        /// </summary>
        public static string SearchAddress_SelectYourAddressMessage {
            get {
                return ResourceManager.GetString("SearchAddress_SelectYourAddressMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Use Selected Address.
        /// </summary>
        public static string SearchAddress_UseSelectedAddressButton {
            get {
                return ResourceManager.GetString("SearchAddress_UseSelectedAddressButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to I confirm this is my address..
        /// </summary>
        public static string UseAddress_ConfirmationText {
            get {
                return ResourceManager.GetString("UseAddress_ConfirmationText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirm your address.
        /// </summary>
        public static string UseAddress_PageHeader {
            get {
                return ResourceManager.GetString("UseAddress_PageHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirm your address.
        /// </summary>
        public static string UseAddress_PageTitle {
            get {
                return ResourceManager.GetString("UseAddress_PageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirm.
        /// </summary>
        public static string UseAddress_SubmitButton {
            get {
                return ResourceManager.GetString("UseAddress_SubmitButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The address was not found in our system..
        /// </summary>
        public static string UseAddressConfirmed_AddressNotFoundMessage {
            get {
                return ResourceManager.GetString("UseAddressConfirmed_AddressNotFoundMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your submission has been initiated. You will receive a verification code by mail soon..
        /// </summary>
        public static string UseAddressConfirmed_SuccessMessage {
            get {
                return ResourceManager.GetString("UseAddressConfirmed_SuccessMessage", resourceCulture);
            }
        }
    }
}
