//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Epsilon.Resources.Web.PropertyInfo {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class PropertyInfoResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal PropertyInfoResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Epsilon.Resources.Web.PropertyInfo.PropertyInfoResources", typeof(PropertyInfoResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Accessing the information for this property will will cost you {0} token(s)..
        /// </summary>
        public static string GainAccess_ConfirmationText {
            get {
                return ResourceManager.GetString("GainAccess_ConfirmationText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You already have access to the information for this property. Click the button below to view it..
        /// </summary>
        public static string GainAccess_ExistingPropertyInfoAccess_Message {
            get {
                return ResourceManager.GetString("GainAccess_ExistingPropertyInfoAccess_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to View property information.
        /// </summary>
        public static string GainAccess_ExistingPropertyInfoAccess_ViewInfo_ButtonText {
            get {
                return ResourceManager.GetString("GainAccess_ExistingPropertyInfoAccess_ViewInfo_ButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Access Property Information.
        /// </summary>
        public static string GainAccess_PageHeader {
            get {
                return ResourceManager.GetString("GainAccess_PageHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Access Property Information.
        /// </summary>
        public static string GainAccess_PageTitle {
            get {
                return ResourceManager.GetString("GainAccess_PageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Proceed.
        /// </summary>
        public static string GainAccess_SubmitButtonText {
            get {
                return ResourceManager.GetString("GainAccess_SubmitButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Actions.
        /// </summary>
        public static string MyExploredPropertiesSummary_ActionsColumnHeader {
            get {
                return ResourceManager.GetString("MyExploredPropertiesSummary_ActionsColumnHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to View the information for this property..
        /// </summary>
        public static string MyExploredPropertiesSummary_ActionView_ButtonHoverText {
            get {
                return ResourceManager.GetString("MyExploredPropertiesSummary_ActionView_ButtonHoverText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to View.
        /// </summary>
        public static string MyExploredPropertiesSummary_ActionView_ButtonText {
            get {
                return ResourceManager.GetString("MyExploredPropertiesSummary_ActionView_ButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Address.
        /// </summary>
        public static string MyExploredPropertiesSummary_AddressColumnHeader {
            get {
                return ResourceManager.GetString("MyExploredPropertiesSummary_AddressColumnHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Expiration.
        /// </summary>
        public static string MyExploredPropertiesSummary_ExpiresOnColumnHeader {
            get {
                return ResourceManager.GetString("MyExploredPropertiesSummary_ExpiresOnColumnHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to My Explored Properties.
        /// </summary>
        public static string MyExploredPropertiesSummary_Header {
            get {
                return ResourceManager.GetString("MyExploredPropertiesSummary_Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to My Explored Properties.
        /// </summary>
        public static string MyExploredPropertiesSummary_PageTitle {
            get {
                return ResourceManager.GetString("MyExploredPropertiesSummary_PageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to View all properties.
        /// </summary>
        public static string MyExploredPropertiesSummary_ViewAllLinkText {
            get {
                return ResourceManager.GetString("MyExploredPropertiesSummary_ViewAllLinkText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to My Latest Explored Properties.
        /// </summary>
        public static string MyExploredPropertiesSummary_WithLimit_Header {
            get {
                return ResourceManager.GetString("MyExploredPropertiesSummary_WithLimit_Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Access Information.
        /// </summary>
        public static string SearchProperties_GainAccessButton {
            get {
                return ResourceManager.GetString("SearchProperties_GainAccessButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Address.
        /// </summary>
        public static string SearchProperty_FieldFullAddress_ColumnHeader {
            get {
                return ResourceManager.GetString("SearchProperty_FieldFullAddress_ColumnHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last Submission.
        /// </summary>
        public static string SearchProperty_FieldLastSubmissionOn_ColumnHeader {
            get {
                return ResourceManager.GetString("SearchProperty_FieldLastSubmissionOn_ColumnHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Number of Submissions.
        /// </summary>
        public static string SearchProperty_FieldNumberOfCompletedSubmissions_ColumnHeader {
            get {
                return ResourceManager.GetString("SearchProperty_FieldNumberOfCompletedSubmissions_ColumnHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your search returned more than {0} results. If you cannot find the property you are looking for, please narrow down your search..
        /// </summary>
        public static string SearchProperty_NarrowDownYourSearchMessage {
            get {
                return ResourceManager.GetString("SearchProperty_NarrowDownYourSearchMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No properties found..
        /// </summary>
        public static string SearchProperty_NoPropertiesFoundMessage {
            get {
                return ResourceManager.GetString("SearchProperty_NoPropertiesFoundMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search Property.
        /// </summary>
        public static string SearchProperty_PageHeader {
            get {
                return ResourceManager.GetString("SearchProperty_PageHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search Property.
        /// </summary>
        public static string SearchProperty_PageTitle {
            get {
                return ResourceManager.GetString("SearchProperty_PageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search.
        /// </summary>
        public static string SearchProperty_SearchButton {
            get {
                return ResourceManager.GetString("SearchProperty_SearchButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search terms.
        /// </summary>
        public static string SearchProperty_SearchTermsLabel {
            get {
                return ResourceManager.GetString("SearchProperty_SearchTermsLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Possibly the same property.
        /// </summary>
        public static string ViewInfo_DuplicateProperties_Header {
            get {
                return ResourceManager.GetString("ViewInfo_DuplicateProperties_Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Selected property.
        /// </summary>
        public static string ViewInfo_MainProperty_Header {
            get {
                return ResourceManager.GetString("ViewInfo_MainProperty_Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Property Information.
        /// </summary>
        public static string ViewInfo_PageHeader {
            get {
                return ResourceManager.GetString("ViewInfo_PageHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Property Information.
        /// </summary>
        public static string ViewInfo_PageTitle {
            get {
                return ResourceManager.GetString("ViewInfo_PageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Furnished.
        /// </summary>
        public static string ViewInfo_SubmissionFieldIsFurnished_Header {
            get {
                return ResourceManager.GetString("ViewInfo_SubmissionFieldIsFurnished_Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Part of Property.
        /// </summary>
        public static string ViewInfo_SubmissionFieldIsPartOfProperty_Header {
            get {
                return ResourceManager.GetString("ViewInfo_SubmissionFieldIsPartOfProperty_Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Landlord.
        /// </summary>
        public static string ViewInfo_SubmissionFieldLandlordRating_Header {
            get {
                return ResourceManager.GetString("ViewInfo_SubmissionFieldLandlordRating_Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Neighbours.
        /// </summary>
        public static string ViewInfo_SubmissionFieldNeighboursRating_Header {
            get {
                return ResourceManager.GetString("ViewInfo_SubmissionFieldNeighboursRating_Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bedrooms.
        /// </summary>
        public static string ViewInfo_SubmissionFieldNumberOfBedrooms_Header {
            get {
                return ResourceManager.GetString("ViewInfo_SubmissionFieldNumberOfBedrooms_Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Property Condition.
        /// </summary>
        public static string ViewInfo_SubmissionFieldPropertyConditionRating_Header {
            get {
                return ResourceManager.GetString("ViewInfo_SubmissionFieldPropertyConditionRating_Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Monthly Rent.
        /// </summary>
        public static string ViewInfo_SubmissionFieldRentPerMonth_Header {
            get {
                return ResourceManager.GetString("ViewInfo_SubmissionFieldRentPerMonth_Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Submitted.
        /// </summary>
        public static string ViewInfo_SubmissionFieldSubmittedOn_Header {
            get {
                return ResourceManager.GetString("ViewInfo_SubmissionFieldSubmittedOn_Header", resourceCulture);
            }
        }
    }
}
