//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.0
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Epsilon.Resources.Submission {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class SubmissionResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal SubmissionResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Epsilon.Resources.Submission.SubmissionResources", typeof(SubmissionResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add new address.
        /// </summary>
        public static string SearchAddress_AddNewAddressButton {
            get {
                return ResourceManager.GetString("SearchAddress_AddNewAddressButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please add your address to our database..
        /// </summary>
        public static string SearchAddress_AddYourAddressMessage {
            get {
                return ResourceManager.GetString("SearchAddress_AddYourAddressMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your search returned more than {{ addressSearchResponse.ResultsLimit }} addresses. Please narrow down your search..
        /// </summary>
        public static string SearchAddress_NarrowDownYourSearchMessage {
            get {
                return ResourceManager.GetString("SearchAddress_NarrowDownYourSearchMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No addresses found..
        /// </summary>
        public static string SearchAddress_NoAddressesFoundMessage {
            get {
                return ResourceManager.GetString("SearchAddress_NoAddressesFoundMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Find your address.
        /// </summary>
        public static string SearchAddress_PageHeader {
            get {
                return ResourceManager.GetString("SearchAddress_PageHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Find your address.
        /// </summary>
        public static string SearchAddress_PageTitle {
            get {
                return ResourceManager.GetString("SearchAddress_PageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search.
        /// </summary>
        public static string SearchAddress_SearchButton {
            get {
                return ResourceManager.GetString("SearchAddress_SearchButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Use Selected Address.
        /// </summary>
        public static string SearchAddress_UseSelectedAddressButton {
            get {
                return ResourceManager.GetString("SearchAddress_UseSelectedAddressButton", resourceCulture);
            }
        }
    }
}
